#!/bin/bash

echo "🔧 Quick fix for practice schedule RLS policies"
echo "Copy and paste this SQL into your Supabase SQL Editor:"
echo ""
echo "-- Drop all existing practice schedule policies"
echo "DROP POLICY IF EXISTS \"Coaches can read practice schedules\" ON public.practice_schedules;"
echo "DROP POLICY IF EXISTS \"Coaches can insert practice schedules\" ON public.practice_schedules;"
echo "DROP POLICY IF EXISTS \"Coaches can update practice schedules\" ON public.practice_schedules;"
echo "DROP POLICY IF EXISTS \"Team members can read practice schedules\" ON public.practice_schedules;"
echo "DROP POLICY IF EXISTS \"Coaches can manage practice schedules\" ON public.practice_schedules;"
echo ""
echo "-- Create simplified policies (no table references)"
echo "CREATE POLICY \"Coaches can manage practice schedules\" ON public.practice_schedules"
echo "    FOR ALL USING ("
echo "        (auth.jwt() ->> 'user_metadata')::jsonb ->> 'role' = 'coach'"
echo "    );"
echo ""
echo "CREATE POLICY \"Team members can read practice schedules\" ON public.practice_schedules"
echo "    FOR SELECT USING ("
echo "        (auth.jwt() ->> 'user_metadata')::jsonb ->> 'role' IN ('athlete', 'captain', 'coach')"
echo "    );"
echo ""
echo "✅ This should fix the infinite recursion error!"
